all:
  hosts:
    vm1:
  children:
    app:
      hosts:
        vm2:
          ansible_user: ubuntu
        vm3:
          ansible_user: cloud-user
    database:
      ver: 5.6
      dir: /var/lib/postgres
      hosts:
        vm1:
    web:
      hosts:
        vm1:
          ansible_user: ubuntu
