all:
  hosts:
    vm1:
  children:
    app:
      hosts:
        vm2:
          ansible_user: ubuntu
        vm3:
          ansible_user: cloud-user
    database:
      hosts:
        vm1:
      vars:
        ver: 12 
        dir: /var/lib/postgresql
    web:
      hosts:
        vm1:
          ansible_user: ubuntu
