---

- hosts: app 
  gather_facts: yes 
  become: yes

  tasks:

  - name: docker install on centos
    include_tasks: centos_docker.yml
    when: (ansible_distribution == "CentOS")

  - name: docker install on ubuntu 
    include_tasks: ubuntu_docker.yml
    when: (ansible_distribution == "Ubuntu")

- hosts: database
  gather_facts: yes 
  become: yes

  tasks:

  - name: Add key for Postgres repo
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Add Postgres repo to sources list
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main' state=present

  - name: postgresql-server install
    apt:
      name: postgresql-{{ ver }}
      state: present
 
  - name: Change dir for postgresql base
    postgresql_set:
      name: data_directory
      value: '/var/lib/postgresql'
      become_user: postgres
