---

- hosts: app 
  gather_facts: yes 
  become: yes

  tasks:

  - name: docker install on centos
    include_tasks: centos_docker.yml
    when: (ansible_distribution == "CentOS")

  - name: docker install on ubuntu 
    include_tasks: ubuntu_docker.yml
    when: (ansible_distribution == "Ubuntu")

- hosts: database
  gather_facts: yes 
  become: yes

  tasks:

  - name: Add key for Postgres repo
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Add Postgres repo to sources list
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main' state=present

  - name: postgresql-server install
    apt:
      name: postgresql-{{ ver }}
      state: present
 
  - name: Change dir for postgresql base
    lineinfile:
      dest: /etc/postgresql/{{ ver }}/main/postgresql.conf 
      regexp: '^data_directory'
      insertafter: '^#data_directory'
      line: data_directory = '{{ dir }}'

  - name: —Åreate new directory for postgresql
    file: path="{{ dir }}" state=directory

  - name: get file names to copy
    command: "find /var/lib/postgresql/{{ ver }}/main -type f"
    register: files_to_copy

  - name: copy files
    copy:
      src: "{{ item }}"
      dest: "{{ dir }}"
      owner: postgres 
      group: postgres 
      mode: 0644
      with_items:
      - "{{ files_to_copy.stdout_lines }}"

  - name: Restart postgresql
    systemd:
      name: postgresql
      state: restarted 
