---

- hosts: app 
  gather_facts: yes 
  become: yes

  tasks:

  - name: docker install on centos
    include_tasks: centos_docker.yml
    when: (ansible_distribution == "CentOS")

  - name: docker install on ubuntu 
    include_tasks: ubuntu_docker.yml
    when: (ansible_distribution == "Ubuntu")

- hosts: database
  gather_facts: yes 
  become: yes

  tasks:

  - name: Add key for Postgres repo
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Add Postgres repo to sources list
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main' state=present

  - name: postgresql-server install
    apt:
      name: postgresql-{{ ver }}
      state: present
 
  - name: Change dir for postgresql base
    lineinfile:
      dest: /etc/postgresql/{{ ver }}/main/postgresql.conf 
      regexp: '^data_directory'
      insertafter: '^#data_directory'
      line: data_directory = '{{ dir }}'

  - name: —Åreate new directory for postgresql
    file: 
      path: "{{ dir }}"
      owner: postgres
      group: postgres
      state: directory

  - name: copy files for postgresql base
    command: cp -r /var/lib/postgresql/{{ ver }}/main/. {{ dir }}/

  - name: Change owner and group
    file:
      path: "{{ dir }}"
      owner: postgres
      group: postgres

  - name: Restart postgresql
    systemd:
      name: postgresql
      state: restarted